# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Khor Shao Liang
tagline:             'Software Engineer'
description:         'I am a final year student in School of Computing at National University of Singapore. I am pursuing a Bachelor of Computing (Computer Science) specializing in Database Systems.'
url:                 https://khorsl.github.io/blog/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Khor Shao Liang
  url:               https://www.linkedin.com/in/khorshaoliang/
  email:             stephenksl@gmail.com

# Custom vars
version:             1.0.0
